2019-11-18 19:42:34,751 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-11-18 19:42:37,819 [INFO] loggerApp.views: this is an info response
2019-11-18 19:43:28,930 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-11-18 19:44:32,759 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-11-18 19:44:40,341 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-11-18 19:49:21,073 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-11-18 19:49:31,411 [INFO] loggerApp.views: this is an info response
2019-11-18 19:49:31,734 [INFO] loggerApp.views: this is an info response
2019-11-18 19:49:32,004 [INFO] loggerApp.views: this is an info response
2019-12-12 11:31:31,959 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 11:31:37,450 [WARNING] django.request: Not Found: /
2019-12-12 11:31:37,950 [WARNING] django.request: Not Found: /favicon.ico
2019-12-12 11:32:09,068 [INFO] loggerApp.views: this is an info response
2019-12-12 11:33:17,158 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 11:33:17,732 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 11:33:20,516 [INFO] loggerApp.views: this is an info response
2019-12-12 11:36:49,443 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 11:36:50,013 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 11:36:51,234 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 11:36:51,646 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 11:36:53,921 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/urls.py changed, reloading.
2019-12-12 11:36:54,259 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 11:37:01,584 [WARNING] django.request: Not Found: /loggerApp/value
2019-12-12 11:37:15,048 [INFO] loggerApp.views: this is an info response
2019-12-12 11:37:31,279 [WARNING] django.request: Not Found: /loggerApp/index/
2019-12-12 11:41:55,313 [WARNING] django.request: Not Found: /loggerApp/index/
2019-12-12 11:43:34,341 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 11:43:35,058 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 11:43:39,783 [INFO] loggerApp.views: this is an info response
2019-12-12 11:43:39,783 [WARNING] django.request: Not Found: /loggerApp/index/1
2019-12-12 11:44:03,289 [INFO] loggerApp.views: this is an info response
2019-12-12 11:44:03,289 [WARNING] django.request: Not Found: /loggerApp/index/1
2019-12-12 12:14:31,246 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:14:31,889 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:14:47,284 [WARNING] django.request: Not Found: /loggerApp/indexPost
2019-12-12 12:20:34,432 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:20:35,093 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:20:38,083 [WARNING] django.request: Not Found: /loggerApp/indexPost
2019-12-12 12:21:11,353 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/urls.py changed, reloading.
2019-12-12 12:21:11,711 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:21:38,224 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /loggerApp/indexPost
2019-12-12 12:22:42,940 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:22:43,538 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:22:46,738 [ERROR] django.request: Internal Server Error: /loggerApp/indexPost
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 20, in indexPost
    data=json.loads(request.body)
NameError: name 'json' is not defined
2019-12-12 12:31:01,068 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:31:01,741 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:31:05,838 [ERROR] django.request: Internal Server Error: /loggerApp/indexPost
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 21, in indexPost
    data=json.loads(request.body)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-12-12 12:37:22,026 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:37:22,673 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:37:40,750 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:37:41,262 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:37:51,923 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:37:52,243 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:38:23,010 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:38:23,362 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:38:29,817 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:38:30,140 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:38:32,981 [ERROR] django.request: Internal Server Error: /loggerApp/indexPost
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 21, in indexPost
    data=json.loads(request.body.decode("utf-8"))
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-12-12 12:42:39,642 [ERROR] django.request: Internal Server Error: /loggerApp/indexPost
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 21, in indexPost
    data=json.loads(request.body.decode("utf-8"))
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-12-12 12:42:49,535 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:42:50,164 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:42:53,015 [ERROR] django.request: Internal Server Error: /loggerApp/indexPost
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 20, in indexPost
    data=request.POST['data']
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'data'
2019-12-12 12:43:23,208 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:43:23,535 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:43:26,252 [ERROR] django.request: Internal Server Error: /loggerApp/indexPost
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 21, in indexPost
    data=request.POST['data']
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'data'
2019-12-12 12:44:45,429 [ERROR] django.request: Internal Server Error: /loggerApp/indexPost
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 21, in indexPost
    data=request.POST['data']
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'data'
2019-12-12 12:47:40,457 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:47:41,134 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:51:16,028 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 12:51:16,373 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 12:51:32,613 [ERROR] django.request: Internal Server Error: /loggerApp/indexPost
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 24, in indexPost
    data=data['data']
KeyError: 'data'
2019-12-12 13:14:42,076 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 13:14:42,702 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:15:17,732 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 13:15:18,092 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:17:40,239 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 13:17:40,928 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:17:57,995 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:17:58,324 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:18:02,855 [ERROR] django.request: Internal Server Error: /loggerApp/index/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: innerfunc() got an unexpected keyword argument 'stringParameter'
2019-12-12 13:18:39,843 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:18:40,258 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:18:42,142 [ERROR] django.request: Internal Server Error: /loggerApp/index/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 3, in innerfunc
    data=func()
TypeError: index() missing 2 required positional arguments: 'request' and 'stringParameter'
2019-12-12 13:18:56,303 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:18:56,656 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:18:58,429 [INFO] loggerApp.views: this is an info response
2019-12-12 13:18:58,431 [ERROR] django.request: Internal Server Error: /loggerApp/index/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 4, in innerfunc
    return JsonResonse(data)
NameError: name 'JsonResonse' is not defined
2019-12-12 13:19:33,897 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:19:34,234 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:19:37,783 [INFO] loggerApp.views: this is an info response
2019-12-12 13:19:37,788 [ERROR] django.request: Internal Server Error: /loggerApp/index/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 8, in innerfunc
    return JsonResponse(data)
  File "/usr/local/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2019-12-12 13:19:51,381 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:19:51,797 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:19:53,319 [INFO] loggerApp.views: this is an info response
2019-12-12 13:19:53,321 [ERROR] django.request: Internal Server Error: /loggerApp/index/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 8, in innerfunc
    return JsonResponse(data,safe=False)
  File "/usr/local/lib/python3.7/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type JsonResponse is not JSON serializable
2019-12-12 13:20:15,334 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:20:15,700 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:20:17,071 [INFO] loggerApp.views: this is an info response
2019-12-12 13:20:17,076 [ERROR] django.request: Internal Server Error: /loggerApp/index/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 8, in innerfunc
    return HttpResponse(data,safe=False)
  File "/usr/local/lib/python3.7/site-packages/django/http/response.py", line 289, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'safe'
2019-12-12 13:20:25,445 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:20:25,841 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:20:29,250 [INFO] loggerApp.views: this is an info response
2019-12-12 13:20:40,842 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:20:41,252 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:21:17,374 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 13:21:17,737 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:21:19,928 [INFO] loggerApp.views: this is an info response
2019-12-12 13:23:10,328 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:23:11,069 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:23:14,160 [INFO] loggerApp.views: this is an info response
2019-12-12 13:23:14,165 [ERROR] django.request: Internal Server Error: /loggerApp/index/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 9, in innerfunc
    return JsonResponse(data)
  File "/usr/local/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2019-12-12 13:23:26,076 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 13:23:26,620 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:23:29,033 [INFO] loggerApp.views: this is an info response
2019-12-12 13:34:22,842 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:34:23,425 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:35:39,694 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:35:40,031 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:35:46,816 [WARNING] django.request: Not Found: /loggerApp/index/1/2
2019-12-12 13:40:41,771 [WARNING] django.request: Not Found: /loggerApp/index/1/2
2019-12-12 13:40:59,658 [WARNING] django.request: Not Found: /loggerApp/index/
2019-12-12 13:41:01,100 [WARNING] django.request: Not Found: /loggerApp/index/
2019-12-12 13:41:02,291 [WARNING] django.request: Not Found: /loggerApp/index
2019-12-12 13:41:05,590 [INFO] loggerApp.views: this is an info response
2019-12-12 13:54:02,127 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 13:54:02,814 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:54:05,342 [ERROR] django.request: Internal Server Error: /loggerApp/index/2
Traceback (most recent call last):
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 8, in innerfunc
    data=func(*args,**kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 13, in index
    a=1/0
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 9, in innerfunc
    except e:
NameError: name 'e' is not defined
2019-12-12 13:54:12,537 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:54:12,876 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:54:15,502 [ERROR] django.request: Internal Server Error: /loggerApp/index/2
Traceback (most recent call last):
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 8, in innerfunc
    data=func(*args,**kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 13, in index
    a=1/0
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 9, in innerfunc
    except e:
NameError: name 'e' is not defined
2019-12-12 13:54:37,395 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 13:54:37,794 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:55:54,101 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-12-12 13:55:54,450 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 13:55:57,146 [ERROR] django.request: Internal Server Error: /loggerApp/index/2
Traceback (most recent call last):
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 8, in innerfunc
    data=func(*args,**kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 13, in index
    a=1/0
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 9, in innerfunc
    except e:
NameError: name 'e' is not defined
2019-12-12 14:01:24,702 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 14:01:25,366 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:01:27,833 [ERROR] django.request: Internal Server Error: /loggerApp/index/2
Traceback (most recent call last):
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 8, in innerfunc
    func(*args,**kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 13, in index
    a=1/0
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/handler.py", line 9, in innerfunc
    except e:
NameError: name 'e' is not defined
2019-12-12 14:02:44,976 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 14:02:45,523 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:03:38,642 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 14:03:39,163 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:04:01,600 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 14:04:02,196 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:04:04,590 [INFO] loggerApp.views: this is an info response
2019-12-12 14:04:19,395 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 14:04:19,976 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:04:45,589 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 14:04:46,193 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:04:48,457 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 14:04:48,773 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:05:09,131 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/handler.py changed, reloading.
2019-12-12 14:05:09,736 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:07:16,052 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 14:07:16,744 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:12:07,455 [WARNING] django.request: Not Found: /
2019-12-12 14:12:16,124 [WARNING] django.request: Not Found: /loggerApp/index/2/1
2019-12-12 14:12:22,180 [INFO] loggerApp.views: this is an info response
2019-12-12 14:22:50,179 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 14:22:50,859 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:23:25,837 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 14:23:26,391 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:29:44,271 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 14:29:44,934 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:30:03,058 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 14:30:03,385 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:30:33,120 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 14:30:33,679 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:31:48,941 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 14:31:49,545 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:31:57,362 [WARNING] django.request: Not Found: /
2019-12-12 14:32:09,913 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-12-12 14:32:10,524 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:32:12,844 [ERROR] django.request: Internal Server Error: /
2019-12-12 14:32:32,202 [ERROR] django.request: Internal Server Error: /loggerApp/index/2/1
2019-12-12 14:41:53,271 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-12-12 14:41:54,029 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:42:00,838 [ERROR] django.request: Internal Server Error: /loggerApp/indexPost
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mukul/Desktop/loggerVariations/loggerApp/views.py", line 27, in indexPost
    data=data['data']
KeyError: 'data'
2019-12-12 14:45:39,799 [ERROR] django.request: Internal Server Error: /
2019-12-12 14:46:12,834 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 14:46:13,602 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:46:50,756 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 14:46:51,079 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:47:04,920 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 14:47:05,262 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:47:07,965 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 14:47:22,347 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 14:47:22,699 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:47:25,016 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 14:49:40,728 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 14:49:41,426 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:49:43,583 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 14:49:43,583 [INFO] django.request: OK: /loggerApp/indexPost
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view loggerApp.views.indexPost didn't return an HttpResponse object. It returned None instead.
2019-12-12 14:49:49,044 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 14:49:49,449 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:50:43,748 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-12-12 14:50:44,459 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:50:53,491 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2019-12-12 14:50:53,515 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 14:51:54,670 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-12-12 14:51:55,011 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:51:57,295 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 14:52:34,483 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-12-12 14:52:34,805 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:52:37,161 [WARNING] django.request: Not Found: /
2019-12-12 14:52:49,805 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-12-12 14:52:50,136 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:55:47,270 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 14:55:47,907 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:56:39,959 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 14:56:40,520 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:56:43,385 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 14:57:09,325 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-12-12 14:57:09,953 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 14:57:12,325 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 15:01:47,774 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 15:01:48,419 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:01:55,128 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 15:07:46,872 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-12-12 15:07:47,541 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:07:56,660 [WARNING] django.request: Not Found: /
2019-12-12 15:09:21,044 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 15:09:21,597 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:09:23,782 [WARNING] django.request: Not Found: /
2019-12-12 15:10:16,853 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 15:10:17,289 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:10:20,192 [WARNING] django.request: Not Found: /
2019-12-12 15:10:34,501 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/settings.py changed, reloading.
2019-12-12 15:10:34,895 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:10:36,716 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 15:11:01,577 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 15:11:02,193 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:11:04,618 [ERROR] django.request: Internal Server Error: /
2019-12-12 15:11:08,714 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 15:11:09,125 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:12:12,753 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerApp/views.py changed, reloading.
2019-12-12 15:12:13,182 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:12:37,776 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 15:12:38,480 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:12:59,721 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 15:13:00,060 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:13:03,676 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 15:16:37,437 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 15:16:38,183 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:16:41,473 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 15:18:06,244 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 15:18:06,776 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:18:09,908 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 15:19:20,126 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/urls.py changed, reloading.
2019-12-12 15:19:20,742 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:19:23,471 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 15:20:02,208 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 15:20:02,799 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:20:06,127 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 15:20:06,933 [INFO] loggerVariations.errorViews: 500 error has occurred
2019-12-12 15:21:38,363 [INFO] django.utils.autoreload: /Users/mukul/Desktop/loggerVariations/loggerVariations/errorViews.py changed, reloading.
2019-12-12 15:21:39,035 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2019-12-12 15:21:43,197 [INFO] loggerVariations.errorViews: 500 error has occurred
